title: Chinatown Heritage Society of Southern California
logo: /assets/img/chinatown.png
description: Specialization Dossier by Cheeyeon, Chanel, Jana, and Sage.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
